blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  #resources :pages does all below
  #get    '/posts/:post_id/comments',         to: 'comments#index', as 'post_comments'
  #post   '/posts/:post_id/comments',         to: 'comments#create'
  #get    '/posts/:post_id/comments/new',     to: 'comments#new',   as 'new_post_comment'
  #get    '/posts/:post_id/comments/:id',     to: 'comments#show',  as 'post_comment'
  #get    '/posts/:post_id/comments/:id/edit',to: 'comments#eidt',  as 'edit_post_comment'
  #patch  '/posts/:post_id/comments/:id',     to: 'comments#update'
  #delete '/posts/:post_id/comments/:id',     to: 'comments#destroy'

  resources :pages
  get '/pages',to: 'pages#index'
  post '/pages', to:'pages#create'
  #get '/pages/new',to: 'pages#new', as: 'new_page'
  #get '/pages/:id/edit',to: 'pages#edit', as: 'edit_page'
  #get '/pages/:id',to: 'pages#show', as: 'page'
  patch '/pages/:id',to: 'pages#update', as: 'page_update'
  delete '/pages/:id', to: 'pages#destroy'
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
end

blog/app/models/page.rb
class Page < ActiveRecord::Base
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/comment_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[;post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end
  private
  def comment_params
    params.require(:comment).permit(:name, :contect)
end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, except: [:index, :new ,:create]
  #before_action :set_page, only: [:show, :eidt ,:update, :destroy]
  def index
    @pages = Page.all
  end
  def show
    #set_page
  end
  def new
    @page = Page.new
  end

  def create
      @page = Page.new(page_params)
      @page.save
      redirect_to @page
  end

  def edit
    #set_page
  end

 def update
    #set_page
    @page.update(page_params)
    redirect_to @page
 end

 def destroy
    #set_page
    @page.destroy
    redirect_to pages_path
 end

private

def  page_params
  params.require(:page).permit(:title, :body, :slug)
end

def set_page
  @page = Page.find(params[:id])
end

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comment_helper.rb
module CommentHelper
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/comments/_comment.html.erb
<div>
  <strong><%= comment.name %> says:</strong>
  <%= comment.content %>
  </div>

blog/app/views/comments/_form.html.erb
<%= form_for [@post, comment] do |f| %>
 <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
 </div>

 <div class="field">
    <%= f.label :content, "Comment" %>
    <%= f.text_area :content %>
 </div>

 <div class="actions">
   <%= f.submit %>
   </div>

<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

blog/app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

blog/app/views/pages/index.html.erb
<h1>Blog Pages</h1>

<% @pages.each do|page|%>
  <p><%= link_to page.title, page%></p>
<% end %>

<%= link_to 'New Page', new_page_path %>

blog/app/views/pages/new.html.erb
<%= render 'form', page: @page %>

blog/app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p>
  <%= @page.body %>
  <p><%= @page.slug %></p>
</p>
<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Delete', @page, method: :delete %>

blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th><body>
      </body></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
  <h1>Comments</h1>
  <%= render @post.comments %>
  <h2>Add a Comment</h2>
  <%= render partial: "comments/form", locals: {comment: @post.comments.new} %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>